### ISSUE TITLE
Load Custom Extensions

### ISSUE THREAD

**Issue by Squidtito** [TurboWarp/turbowarp.org#27]
Turbowarp cannot access websites like github, to get extension data, but there is a work around.

I will be using [bitwise](https://github.com/TurboWarp/extensions/blob/master/bitwise.js) as a example

click on raw then copy all the code (Control + C) then create a txt file and paste what you copied (Control + V)

save, then make the file type into a ".html" file

open CMD in the folder

Make sure you have python installed, I am using python 3.10, if you don't have python install it from the Microsoft Store

Now, type in CMD "python3.10 -m http.server 8000" if you have a different version of python you prefer then change python3.10 to python(version of python)

You can also put the command I listed in a .bat file so you won't have to enter it every time

now go into Turbowarp, click on extensions, then on custom extensions then type "Localhost:8000"

**Comment by GarboMuffin** [comment]
You're not using that repository correctly. for bitwise you're supposed to use https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/bitwise.js, no workaround needed

**Comment by Squidtito** [comment]
> You're not using that repository correctly. for bitwise you're supposed to use https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/bitwise.js, no workaround needed

this can be used for other things on github, bitwise was just used as a example

**Comment by Squidtito** [comment]
I am sending a edited version of my documentation since github is making errors of me saving it

Turbowarp cannot access websites like github, to get extension data, but there is a work around.

I will be using [bitwise](https://github.com/TurboWarp/extensions/blob/master/bitwise.js) as a example

click on raw then copy all the code (Control + C) then create a txt file and paste what you copied (Control + V)

save, then make the file type into a ".html" file

open CMD in the folder

Make sure you have python installed, I am using python 3.10, if you don't have python install it from the Microsoft Store

Now, type in CMD "python3.10 -m http.server 8000" if you have a different version of python you prefer then change python3.10 to python(version of python)

You can also put the command I listed in a .bat file so you won't have to enter it every time.

now, go into turbowarp, click on extensions, click on custom extensions, and put in "http://localhost:8000/"
