### ISSUE TITLE
Server connection bug

### ISSUE THREAD

**Issue by Squidtito** [TurboWarp/turbowarp.org#28]
Turbowarp when you connect to a custom server https://turbowarp.org/#?cloud_host

I am using "http//base-triangle.at.playit.gg:56807/" but then put wss:// behind that for some reason so this happends "wss://http//base-triangle.at.playit.gg:56807/"

**Comment by GarboMuffin** [comment]
You should doing something like https://turbowarp.org/?cloud_host=wss://base-triangle.at.playit.gg:56807

Once you start using a custom cloud variable server, you are beyond what I am willing or able to provide meaningful support for.
