### ISSUE TITLE
Add a way to post projets with custom extensions on the website.

### ISSUE THREAD

**Issue by Piripe** [TurboWarp/turbowarp.org#39]
You could make a system for posting projects without using Scratch. Something like the way custom extensions are posted.

Btw you could ask projects that pass through this system to add tags or something like that for a potential future search engine.

**Comment by GarboMuffin** [comment]
https://share.turbowarp.org/

**Comment by Evanevoyo** [comment]
> https://share.turbowarp.org/

when is the estimated date when this will be able to support custom JavaScript extensions?

**Comment by GarboMuffin** [comment]
you should assume that share.turbowarp.org is getting no new features

**Comment by GarboMuffin** [comment]
custom JS extensions in particular are probably not ever going to exist in a way that you would want, sorry

the best way to share your project using custom extensions is by packaging them and uploading to some place like itch

**Comment by Evanevoyo** [comment]
ok
