### ISSUE TITLE
Does the turbowarp.org website work?

### ISSUE THREAD

**Issue by sfederici** [TurboWarp/turbowarp.org#48]
I keep getting an infinite loading icon

**Comment by GarboMuffin** [comment]
It's working for me

You might have to tell your browser to do a hard refresh instead of a normal one

Last time this happened to people it was Cloudflare screwing with our requests... Maybe they're doing that again. I'll look tonight

**Comment by GarboMuffin** [comment]
is it still broken for you?

**Comment by sfederici** [comment]
No, it was just a momentary problem
